### ISSUE TITLE
Please consider changing default shortcut keys

### ISSUE THREAD

**Issue by ghost** [MainasuK/Song-Rating#16]
This drove me crazy for a while until I realized it was song rating hijacking the opt1-5 keys & opt-`

Those are used to type ¡™£¢∞àèìòù characters

I personally change them all to use control instead of option

**Comment by MainasuK** [comment]
Sorry for the inconvenience. We cannot resolve this due to what matter the default key binding. The possible conflict always existing. And I'm not sure if there are some languages using the `option` to input the character regularly. I think most of languages using `shift` key.

The idea to using option is due to we binding the `option + <` and `option + >` to changes the rate up and down. The `control` key is not selected due to system conflict for screen navigation.  Following this pattern the `option + number` added for star rate. 

And the key mapping supports customize to change what you want. Changing the key mapping will surprise existing users. So please select the binding best fit you should be fine.

**Comment by ghost** [comment]
There are plenty of available unbound key combinations, I'm simply suggesting setting the default to one that doesn't interfere with native behavior.

> Changing the key mapping will surprise existing users.

I'm suggesting changing the default.  Existing users wouldn't be affected.

**Comment by MainasuK** [comment]
I'm not test that changes. Maybe this could only take effect for new users as your mentioned. 

And another reason to choose the `option` as prefix key is make the right hand rate up and down with "<" and ">" possible. So please customize the key binding in preference panel to make it fit your best. 

Maybe I could show the preference window or make a wizard to allow user set it at the first launch. But I'm not available recently. So I'm sorry that's won't fix in the near future.

**Comment by ghost** [comment]
Dude, you’re breaking the ability to ***type***, this is not some random obscure conflict

**Comment by MainasuK** [comment]
I agree with you. 

Although the possible conflict will occurs. The keyboard type should not be override. 
And I will consider make a simple wizard to resolve this problem. Hope the new shortcut not confusing someone.

There is a quick fix in v1.4.3. And the App Store will update later.

Thank you for your feedback.
